---
driver:
  name: ec2
  ## see .kitchen.examplelocal.yml for addl config

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows-2012r2
#  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[win_stig::default]
    verifier:
#      inspec_tests:
#        - test/integration/default/inspec
#        - /Users/peterburkholder/Projects/misc/inspec-stigs/win2012r2member
    attributes:
